spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yexuesong/elm-delivery-config.git
          username: yexuesong218@gmail.com
          password: s218y728l625
  rabbitmq:
    host: 10.11.88.80
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      expose: "*"